<?php

declare(strict_types=1);

namespace BrainCLI\Services\Docs;

/**
 * Detects documentation drift — methods documented in .docs/*.md
 * that no longer exist in source code.
 *
 * Works with scaffold-format docs (generated by DocScaffolder):
 * requires `> **Source:** \`path\`` line and `## Methods` section with `### methodName` headers.
 * Non-scaffold docs are silently skipped (returns null).
 */
class DriftDetector
{
    /**
     * Regex patterns for extracting public methods from source code.
     * Mirrors UndocumentedScanner::LANGUAGE_CONFIGS function_pattern values.
     *
     * @var array<string, string>
     */
    protected const FUNCTION_PATTERNS = [
        'php'        => '/public\s+function\s+(\w+)\s*\(/',
        'javascript' => '/^\s*(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(/m',
        'typescript' => '/^\s*(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*[<(]/m',
        'python'     => '/^\s*def\s+(\w+)\s*\(/m',
        'go'         => '/^\s*func\s+(?:\(\w+\s+\*?\w+\)\s+)?(\w+)\s*\(/m',
    ];

    /**
     * File extension to language mapping.
     *
     * @var array<string, string>
     */
    protected const EXTENSION_MAP = [
        '.php' => 'php',
        '.js'  => 'javascript', '.mjs' => 'javascript', '.cjs' => 'javascript', '.jsx' => 'javascript',
        '.ts'  => 'typescript', '.mts' => 'typescript', '.cts' => 'typescript', '.tsx' => 'typescript',
        '.py'  => 'python',
        '.go'  => 'go',
    ];

    /**
     * Detect documentation drift for a single doc file.
     *
     * @return array{class: string, source: string, stale_methods: array<int, string>}|null
     *         Null if doc is not scaffold-format, source not found, or no drift detected.
     */
    public function detect(string $docContent, string $projectDir): ?array
    {
        $parsed = $this->parseDocFile($docContent);

        if ($parsed === null) {
            return null;
        }

        $sourcePath = rtrim($projectDir, '/') . '/' . ltrim($parsed['source'], '/');

        if (!file_exists($sourcePath)) {
            return null;
        }

        $sourceContent = file_get_contents($sourcePath);

        if ($sourceContent === false || $sourceContent === '') {
            return null;
        }

        $sourceMethods = $this->extractSourceMethods($sourceContent, $sourcePath);
        $staleMethods = array_values(array_diff($parsed['methods'], $sourceMethods));

        if (empty($staleMethods)) {
            return null;
        }

        return [
            'class'         => $parsed['class'],
            'source'        => $parsed['source'],
            'stale_methods' => $staleMethods,
        ];
    }

    /**
     * Parse a scaffold-format doc file to extract class name, source path, and documented methods.
     *
     * @return array{class: string, source: string, methods: array<int, string>}|null
     */
    protected function parseDocFile(string $content): ?array
    {
        // Extract YAML name
        if (!preg_match('/^---\s*(.*?)\s*---/s', $content, $yamlMatch)) {
            return null;
        }

        if (!preg_match('/^name:\s*["\']?([^"\'\n]+)["\']?\s*$/m', $yamlMatch[1], $nameMatch)) {
            return null;
        }

        $className = trim($nameMatch[1]);

        if ($className === '') {
            return null;
        }

        // Extract source path from > **Source:** `path`
        if (!preg_match('/>\s*\*\*Source:\*\*\s*`([^`]+)`/', $content, $sourceMatch)) {
            return null;
        }

        $sourcePath = trim($sourceMatch[1]);

        // Extract ### method headers under ## Methods
        if (!preg_match('/^##\s+Methods\s*$/m', $content)) {
            return null;
        }

        // Get content from ## Methods to next ## or end of file
        $methodsSection = preg_split('/^##\s+Methods\s*$/m', $content, 2);

        if (!isset($methodsSection[1])) {
            return null;
        }

        $afterMethods = $methodsSection[1];

        // Cut at next ## (but not ###)
        if (preg_match('/^##\s+[^#]/m', $afterMethods, $nextSection, \PREG_OFFSET_CAPTURE)) {
            $afterMethods = substr($afterMethods, 0, $nextSection[0][1]);
        }

        // Extract ### headers
        preg_match_all('/^###\s+(\w+)\s*$/m', $afterMethods, $methodMatches);

        $methods = $methodMatches[1] ?? [];

        if (empty($methods)) {
            return null;
        }

        return [
            'class'   => $className,
            'source'  => $sourcePath,
            'methods' => array_values($methods),
        ];
    }

    /**
     * Extract public method names from source file content.
     *
     * @return array<int, string>
     */
    protected function extractSourceMethods(string $content, string $filePath): array
    {
        $language = $this->detectLanguage($filePath);

        if ($language === null || !isset(self::FUNCTION_PATTERNS[$language])) {
            return [];
        }

        $pattern = self::FUNCTION_PATTERNS[$language];
        preg_match_all($pattern, $content, $matches);

        $methods = [];
        foreach ($matches[1] ?? [] as $method) {
            // Exclude magic methods (__construct, etc.) and private-convention (_method)
            if (!str_starts_with($method, '__') && !str_starts_with($method, '_')) {
                $methods[] = $method;
            }
        }

        return array_values(array_unique($methods));
    }

    /**
     * Detect programming language from file extension.
     */
    protected function detectLanguage(string $filePath): ?string
    {
        foreach (self::EXTENSION_MAP as $ext => $language) {
            if (str_ends_with($filePath, $ext)) {
                return $language;
            }
        }

        return null;
    }
}
